### ISSUE TITLE
[epic] List of custom assertions / actions

### ISSUE THREAD

**Issue by mattgrill** [jsdrupal/drupal#2]
Thanks @dawehner

Things we should validate:

* What makes sense in JS
* What already exists in nightwatch and we should not duplicate. Having some form of "BC" layer would help to port the existing tests though
* Figure out whether we want all the negations etc.

## Custom commands

Coming from ```core/tests/Drupal/Tests/BrowserTestBase.php```.

* [ ] login
* [ ] get the current URL
* [ ] Click a link
* [ ] Do an select
* [ ] Handle batch pages
* [ ] Provide a nice way to fill a form with many values instead of setting values individually?

## Custom asserts

Coming from ```vendor/behat/mink/src/WebAssert.php``` as well as ```core/tests/Drupal/Tests/WebAssert.php```.

* [ ] buttonExists
* [ ] buttonNotExists
* [ ] selectExists
* [ ] optionExists
* [ ] optionNotExists
* [ ] titleEquals
* [ ] linkExists
* [ ] linkExistsExact
* [ ] linkNotExists
* [ ] linkNotExistsExact
* [ ] linkByHrefExists
* [ ] linkByHrefNotExists
* [ ] assertNoEscaped
* [ ] assertEscaped
* [ ] fieldDisabled
* [ ] hiddenFieldExists
* [ ] hiddenFieldNotExists
* [ ] hiddenFieldValueEquals
* [ ] hiddenFieldValueNotEquals
* [ ] addressEquals
* [ ] addressNotEquals
* [ ] addressMatches
* [ ] cookieEquals
* [ ] cookieExists
* [ ] pageTextContains
* [ ] pageTextNotContains
* [ ] pageTextMatches
* [ ] pageTextNotMatches
* [ ] responseContains
* [ ] responseNotContains
* [ ] responseMatches
* [ ] responseNotMatches
* [ ] elementsCount
* [ ] elementExists
* [ ] elementNotExists
* [ ] elementTextContains
* [ ] elementTextNotContains
* [ ] elementContains
* [ ] elementNotContains
* [ ] elementAttributeExists
* [ ] elementAttributeContains
* [ ] elementAttributeNotContains
* [ ] fieldExists
* [ ] fieldNotExists
* [ ] fieldValueEquals
* [ ] fieldValueNotEquals
* [ ] checkboxChecked
* [ ] checkboxNotChecked
*
